
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Text.Json;


namespace cfg
{
public sealed partial class StartMachineConfig : Luban.BeanBase
{
    public StartMachineConfig(JsonElement _buf) 
    {
        Id = _buf.GetProperty("Id").GetInt32();
        InnerIP = _buf.GetProperty("InnerIP").GetString();
        OuterIP = _buf.GetProperty("OuterIP").GetString();
        WatcherPort = _buf.GetProperty("WatcherPort").GetString();
    }

    public static StartMachineConfig DeserializeStartMachineConfig(JsonElement _buf)
    {
        return new StartMachineConfig(_buf);
    }

    /// <summary>
    /// 这是id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 内网地址
    /// </summary>
    public readonly string InnerIP;
    /// <summary>
    /// 外网地址
    /// </summary>
    public readonly string OuterIP;
    /// <summary>
    /// 守护进程端口
    /// </summary>
    public readonly string WatcherPort;
   
    public const int __ID__ = 1628109127;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "InnerIP:" + InnerIP + ","
        + "OuterIP:" + OuterIP + ","
        + "WatcherPort:" + WatcherPort + ","
        + "}";
    }
}

}
