
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Text.Json;


namespace cfg
{
public partial class StartProcessTable
{
    private readonly System.Collections.Generic.Dictionary<int, StartProcessConfig> _dataMap;
    private readonly System.Collections.Generic.List<StartProcessConfig> _dataList;
    
    public StartProcessTable(JsonElement _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, StartProcessConfig>();
        _dataList = new System.Collections.Generic.List<StartProcessConfig>();
        
        foreach(JsonElement _ele in _buf.EnumerateArray())
        {
            StartProcessConfig _v;
            _v = StartProcessConfig.DeserializeStartProcessConfig(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, StartProcessConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<StartProcessConfig> DataList => _dataList;

    public StartProcessConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public StartProcessConfig Get(int key) => _dataMap[key];
    public StartProcessConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

