
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Text.Json;


namespace luban
{
public sealed partial class StartSceneConfig : Luban.BeanBase
{
    public StartSceneConfig(JsonElement _buf) 
    {
        Id = _buf.GetProperty("Id").GetInt32();
        Process = _buf.GetProperty("Process").GetInt32();
        Zone = _buf.GetProperty("Zone").GetInt32();
        SceneType = _buf.GetProperty("SceneType").GetString();
        Name = _buf.GetProperty("Name").GetString();
        Port = _buf.GetProperty("Port").GetInt32();
    }

    public static StartSceneConfig DeserializeStartSceneConfig(JsonElement _buf)
    {
        return new StartSceneConfig(_buf);
    }

    /// <summary>
    /// Id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 所属进程
    /// </summary>
    public readonly int Process;
    /// <summary>
    /// 所属区
    /// </summary>
    public readonly int Zone;
    /// <summary>
    /// 类型
    /// </summary>
    public readonly string SceneType;
    /// <summary>
    /// 名字
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 外网端口
    /// </summary>
    public readonly int Port;
   
    public const int __ID__ = 1499456844;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Process:" + Process + ","
        + "Zone:" + Zone + ","
        + "SceneType:" + SceneType + ","
        + "Name:" + Name + ","
        + "Port:" + Port + ","
        + "}";
    }
}

}
