
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Text.Json;


namespace luban
{
public partial class StartMachineTable
{
    private readonly System.Collections.Generic.Dictionary<int, StartMachineConfig> _dataMap;
    private readonly System.Collections.Generic.List<StartMachineConfig> _dataList;
    
    public StartMachineTable(JsonElement _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, StartMachineConfig>();
        _dataList = new System.Collections.Generic.List<StartMachineConfig>();
        
        foreach(JsonElement _ele in _buf.EnumerateArray())
        {
            StartMachineConfig _v;
            _v = StartMachineConfig.DeserializeStartMachineConfig(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, StartMachineConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<StartMachineConfig> DataList => _dataList;

    public StartMachineConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public StartMachineConfig Get(int key) => _dataMap[key];
    public StartMachineConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

