
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Text.Json;


namespace luban
{
public partial class StartSceneTable
{
    private readonly System.Collections.Generic.Dictionary<int, StartSceneConfig> _dataMap;
    private readonly System.Collections.Generic.List<StartSceneConfig> _dataList;
    
    public StartSceneTable(JsonElement _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, StartSceneConfig>();
        _dataList = new System.Collections.Generic.List<StartSceneConfig>();
        
        foreach(JsonElement _ele in _buf.EnumerateArray())
        {
            StartSceneConfig _v;
            _v = StartSceneConfig.DeserializeStartSceneConfig(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, StartSceneConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<StartSceneConfig> DataList => _dataList;

    public StartSceneConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public StartSceneConfig Get(int key) => _dataMap[key];
    public StartSceneConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

