
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Text.Json;


namespace luban
{
public sealed partial class StartProcessConfig : Luban.BeanBase
{
    public StartProcessConfig(JsonElement _buf) 
    {
        Id = _buf.GetProperty("Id").GetInt32();
        MachineId = _buf.GetProperty("MachineId").GetInt32();
        Port = _buf.GetProperty("Port").GetInt32();
    }

    public static StartProcessConfig DeserializeStartProcessConfig(JsonElement _buf)
    {
        return new StartProcessConfig(_buf);
    }

    /// <summary>
    /// Id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 所属机器
    /// </summary>
    public readonly int MachineId;
    /// <summary>
    /// 内网端口
    /// </summary>
    public readonly int Port;
   
    public const int __ID__ = 2140444015;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "MachineId:" + MachineId + ","
        + "Port:" + Port + ","
        + "}";
    }
}

}
