
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Text.Json;


namespace luban
{
public sealed partial class StartZoneConfig : Luban.BeanBase
{
    public StartZoneConfig(JsonElement _buf) 
    {
        Id = _buf.GetProperty("Id").GetInt32();
        DBConnection = _buf.GetProperty("DBConnection").GetString();
        DBName = _buf.GetProperty("DBName").GetString();
        Desc = _buf.GetProperty("Desc").GetString();
    }

    public static StartZoneConfig DeserializeStartZoneConfig(JsonElement _buf)
    {
        return new StartZoneConfig(_buf);
    }

    /// <summary>
    /// Id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 数据库地址
    /// </summary>
    public readonly string DBConnection;
    /// <summary>
    /// 数据库名
    /// </summary>
    public readonly string DBName;
    /// <summary>
    /// 说明
    /// </summary>
    public readonly string Desc;
   
    public const int __ID__ = -457316368;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "DBConnection:" + DBConnection + ","
        + "DBName:" + DBName + ","
        + "Desc:" + Desc + ","
        + "}";
    }
}

}
